# Generated by Django 4.0.3 on 2022-03-15 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploading', '0002_post_delete_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_link',
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
    ]
