# Generated by Django 4.0.3 on 2022-03-15 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
    ]
